export const SET_APP_DATA = 'SET_APP_DATA';
export const GET_TODO_TASKS_DATA = 'SET_TASKS_DATA';
export const CHANGE_FILTER_DATA = "CHANGE_FILTER_DATA";
export const SET_FILTER_DATA = "SET_FILTER_DATA";
export const GET_TASKS_DATA = "GET_TASKS_DATA";
export const GET_TODO_TASKS_FILTERED = "GET_TASKS_DATA_FILTERED";